### ISSUE TITLE
OwnCloud image does not work with mounted volume

### ISSUE THREAD

**Issue by outcoldman** [docker-library/owncloud#2]
My docker-compose.yml file (I also use nginx proxy)

```
vdata:
  image: busybox
  volumes:
    - /var/www/html

owncloud:
  hostname: owncloud
  image: owncloud:8.1.0
  volumes_from:
    - vdata
  environment:
    - VIRTUAL_HOST=owncloud.example.com
    - VIRTUAL_PORT=80
  mem_limit: 4g
  cpu_shares: 512
  restart: always
```

Logs shows me 

```
owncloud_1 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.192. Set the 'ServerName' directive globally to suppress this message
owncloud_1 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.192. Set the 'ServerName' directive globally to suppress this message
owncloud_1 | PHP Warning:  Module 'curl' already loaded in Unknown on line 0
owncloud_1 | PHP Warning:  Module 'iconv' already loaded in Unknown on line 0
owncloud_1 | PHP Warning:  Module 'json' already loaded in Unknown on line 0
owncloud_1 | PHP Warning:  Module 'SimpleXML' already loaded in Unknown on line 0
owncloud_1 | PHP Warning:  Module 'xml' already loaded in Unknown on line 0
owncloud_1 | PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0
owncloud_1 | [Tue Jul 28 16:44:21.068950 2015] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.4.43 configured -- resuming normal operations
owncloud_1 | [Tue Jul 28 16:44:21.068978 2015] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
owncloud_1 | [Tue Jul 28 16:44:35.703072 2015] [autoindex:error] [pid 7] [client 172.17.0.115:42909] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
owncloud_1 | 172.17.0.115 - - [28/Jul/2015:16:44:35 +0000] "GET / HTTP/1.1" 403 400 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
owncloud_1 | 172.17.0.115 - - [28/Jul/2015:16:44:35 +0000] "GET /favicon.ico HTTP/1.1" 404 400 "https://owncloud.outcold.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
```

I manually did the steps from entrypoint

```
tar cf - --one-file-system -C /usr/src/owncloud . | tar xf -
chown -R www-data /var/www/html
```

And now everything works

Seems like this if does not work https://github.com/docker-library/owncloud/blob/master/8.1/docker-entrypoint.sh#L4

No idea why
