### ISSUE TITLE
link postgresql/mysql containerized with owncloud

### ISSUE THREAD

**Issue by hugoliv** [docker-library/owncloud#7]
Hello,

Is there any way to link this official owncloud container with official postgresql or mysql container ?

**Comment by tianon** [comment]
The easiest way would be to use something like "--link some-mysql:mysql" or
"--link some-postgres:postgres" and then use "mysql" or "postgres" as the
"database host name" respectively (taking advantage of the "/etc/hosts"
entry container linking adds and keeps updated).  We probably ought to talk
about this a little bit in the docs for the image, too.

**Comment by hugoliv** [comment]
Thanks for your answer. Maybe something is wrong here (using docker-compose):

```
 owncloud:
   image: owncloud:8.0
   links:
     - postgresowncloud:postgres
   environment:
     - VIRTUAL_HOST=sub.domain.com
   volumes:
     - /srv/docker/owncloud/files:/usr/share/webapps/owncloud/data
     - /srv/docker/owncloud/config/:/etc/webapps/owncloud/config

 postgresowncloud:
   image: postgres
   environment:
     - POSTGRES_PASSWORD=owncloud
   volumes:
     - /srv/docker/owncloud/data:/var/lib/postgresql/data
```

Then, I reach sub.domain.com and select postgresql as database with:
- user: postgres
- password: owncloud
- database name: owncloud
- localhost: postgres

And the result is:

```
 Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: could not find driver
```

![pb](https://cloud.githubusercontent.com/assets/4832281/9004375/bc0bfb58-3775-11e5-91c8-4ce38e1e7b6a.png)
