### ISSUE TITLE
Owncloud and LDAP: internal server error

### ISSUE THREAD

**Issue by DivCorleone** [docker-library/owncloud#83]
I have try to make a docker-compose with owncloud, postgres, ldap and phpldapadmin. Everything went ok, until i configure LDAP in owncloud. Now restarting the dockers make owncloud go internal server error 500, if i delete the persistent data on my machine it **starts correctly**. 

Here is my docker-compose.yml:

```
owncloud:
  image: owncloud
  ports:
   - 80:80
  volumes_from:
    - owncloudData
  links:
   - postgres:owncloud-db
   - ldap:owncloud-ldap
  hostname: cloud
  domainname: cloud.example.org

postgres:
  image: postgres
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=password
  volumes:
    - /etc/postgresql:/etc/postgresql
    - /var/lib/postgresql:/var/lib/postgresql

phpldapadmin:
  image: osixia/phpldapadmin
  links:
   - ldap:ldap-host
  environment:
   - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
  hostname: phpldapadmin-service
  
ldap:
  image: osixia/openldap
  volumes:
   - /var/lib/ldap:/var/lib/ldap
   - /etc/ldap/slapd.d:/etc/ldap/slapd.d
  hostname: ldap-service

owncloudData:
  image: owncloud
  command: /bin/bash -c "/bin/chown -R 33 /var/www/html/data && /bin/chown -R 33 /var/www/html/config && /bin/chown -R 33 /var/www/html/apps"
  volumes:
    - /var/www/html/data:/var/www/html/data
    - /var/www/html/config:/var/www/html/config
    - /var/www/html/apps:/var/www/html/apps

```

and the server notification when trying to acces to the cloud :
`[12/Dec/2016:13:24:05 +0000] "GET /favicon.ico HTTP/1.1" 404 502 "http://172.17.0.1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36"`
